# Generated by Django 4.1.4 on 2022-12-12 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_remove_record_authorid_alter_record_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='data',
            new_name='date',
        ),
    ]
